services:
  - type: web
    name: theia-on-render
    env: docker
    dockerfilePath: ./Dockerfile
    plan: starter
    envVars:
      - key: PORT
        value: 3000
    startCommand: echo "Using Docker CMD"