services:
  - type: web
    name: theia-on-render
    env: docker
    dockerfilePath: ./Dockerfile
    plan: starter
    envVars:
      - key: NODE_ENV
        value: production
      - key: PORT
        value: 3000
    # DockerのCMDを使用するため、startCommandは指定しない